server:
  port: 443
  ssl:
    key-alias: alias
    key-store-password: i4kim12j
    key-store-type: PKCS12
    key-store: classpath:api.flysean.love.pfx

orion:
  jwt:
    tokenHeader: Authorization      # JWT存储的请求头
    secret: TRH6PbKcMGEcA6nkm3x9Rl2n-dk0CONml2fKZj8pFwA            # JWT加解密使用的密钥
    expiration: 604800              # JWT的超期限时间(60*60*24*7)
    tokenHead: 'Bearer '            # JWT负载中拿到开头
